default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: wack_development

test:
  <<: *default
  database: wack_test

production:
  <<: *default
  database: wack_production
  username: wack
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>
