#this approach developed with Josh from Zapi at Ruby hacknight

default: &default

 styles:
  - Acroyoga
  - Cardio
  - Dancefitness
  - Handstand
  - HIIT
  - Mobility
  - Partner
  - Strength
  - Warmup
  - Yoga
  - Other

 intensities:
  - Low
  - Medium
  - High

 bodyfocus:
  - Lower Body
  - Hamstring
  - Hip
  - Core
  - Upper Body
  - Full Body
  - Mind
  - Skill

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
