#this approach developed with Josh from Zapi at Ruby hacknight

default: &default

 styles:
  - Acroyoga
  - Cardio
  - Dancefitness
  - Handstand
  - HIIT
  - Mobility
  - Partner
  - Strength
  - Warmup
  - Yoga
  - Other

 intensities:
  - Chilled Wack
  - Power Wack

 bodyfocus:
  - LowerBody
  - Hamstring
  - Hip
  - Core
  - UpperBody
  - FullBody
  - Mind
  - Skill
  - Sleep

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
