#this approach developed with Josh from Zapi at Ruby hacknight

default: &default

 styles:
  - Acroyoga
  - Callisthenics
  - Cardio
  - Dancefitness
  - Flexibility
  - HIIT
  - Mobility
  - Partner
  - Strength
  - Therapeutic
  - Yoga
  - Other

 intensities:
  - Chilled Wack
  - Power Wack

 bodyfocus:
  - LowerBody
  - Hamstring
  - Hip
  - Core
  - UpperBody
  - Wrist
  - FullBody
  - Mind
  - Skill
  - Sleep


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
