#this approach developed with Josh from Zapi at Ruby hacknight

default: &default

 styles:
  - Cardio
  - HIIT
  - Mobility
  - Partner
  - Strength
  - Warmup
  - Yoga
  - Other

 intensities:
  - Low
  - Medium
  - High

 bodyfocus:
  - Lower
  - Hamstring
  - Hip
  - Core
  - Upper
  - Full Body
  - Mind

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
